"""Tests for the TikZ Exporter agent."""

from __future__ import annotations

import pytest

from paperbanana.agents.tikz_exporter import TikZExporterAgent
from paperbanana.core.types import DiagramType


class MockVLM:
    """Mock VLM provider for testing."""

    name = "mock"
    model_name = "mock-model"

    def __init__(self, response: str = ""):
        self._response = response
        self.last_prompt = None
        self.last_images = None

    async def generate(
        self,
        prompt,
        images=None,
        system_prompt=None,
        temperature=1.0,
        max_tokens=4096,
        response_format=None,
    ):
        self.last_prompt = prompt
        self.last_images = images
        return self._response

    def is_available(self):
        return True


SAMPLE_TIKZ = r"""\begin{tikzpicture}
  \node[draw] (a) at (0,0) {Encoder};
  \node[draw] (b) at (3,0) {Decoder};
  \draw[->] (a) -- (b);
\end{tikzpicture}"""

SAMPLE_PGFPLOTS = r"""\pgfplotsset{compat=1.18}
\begin{tikzpicture}
  \begin{axis}[xlabel=Epoch, ylabel=Loss]
    \addplot coordinates {(1,0.9) (2,0.5) (3,0.2)};
  \end{axis}
\end{tikzpicture}"""


# ── Code extraction ────────────────────────────────────────────────


def test_extract_code_fenced_latex():
    """Extracts code from a ```latex fenced block."""
    raw = f"Here is the TikZ:\n```latex\n{SAMPLE_TIKZ}\n```\nDone."
    assert TikZExporterAgent._extract_code(raw) == SAMPLE_TIKZ


def test_extract_code_fenced_tikz():
    """Extracts code from a ```tikz fenced block."""
    raw = f"```tikz\n{SAMPLE_TIKZ}\n```"
    assert TikZExporterAgent._extract_code(raw) == SAMPLE_TIKZ


def test_extract_code_fenced_pgfplots():
    """Extracts code from a ```pgfplots fenced block."""
    raw = f"```pgfplots\n{SAMPLE_PGFPLOTS}\n```"
    assert TikZExporterAgent._extract_code(raw) == SAMPLE_PGFPLOTS


def test_extract_code_fenced_generic():
    """Extracts code from a generic ``` fenced block."""
    raw = f"```\n{SAMPLE_TIKZ}\n```"
    assert TikZExporterAgent._extract_code(raw) == SAMPLE_TIKZ


def test_extract_code_raw_begin():
    r"""Returns raw response if it starts with \begin."""
    assert TikZExporterAgent._extract_code(SAMPLE_TIKZ) == SAMPLE_TIKZ


def test_extract_code_raw_comment():
    """Returns raw response if it starts with a LaTeX comment."""
    raw = f"% comment\n{SAMPLE_TIKZ}"
    assert TikZExporterAgent._extract_code(raw) == raw


def test_extract_code_fallback():
    """Falls back to trimmed response when no fences or LaTeX markers."""
    raw = "  some random text  "
    assert TikZExporterAgent._extract_code(raw) == "some random text"


# ── Agent properties ───────────────────────────────────────────────


def test_agent_name():
    """agent_name is tikz_exporter."""
    agent = TikZExporterAgent(MockVLM())
    assert agent.agent_name == "tikz_exporter"


# ── Agent run ──────────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_run_returns_tikz_with_header(tmp_path):
    """run() returns TikZ code preceded by a metadata header."""
    # Create a minimal test image
    from PIL import Image

    img = Image.new("RGB", (100, 100), color="white")
    img_path = tmp_path / "test.png"
    img.save(str(img_path))

    fenced_response = f"```tikz\n{SAMPLE_TIKZ}\n```"
    vlm = MockVLM(response=fenced_response)
    agent = TikZExporterAgent(vlm)

    result = await agent.run(
        image_path=str(img_path),
        source_context="test methodology",
        caption="test caption",
        diagram_type=DiagramType.METHODOLOGY,
        description="test description",
        venue="neurips",
        version="0.1.0",
    )

    assert SAMPLE_TIKZ in result
    assert "% Generated by PaperBanana 0.1.0" in result
    assert "% Venue: neurips" in result
    assert "% Diagram type: methodology" in result


@pytest.mark.asyncio
async def test_run_passes_image_to_vlm(tmp_path):
    """run() sends the loaded image to the VLM."""
    from PIL import Image

    img = Image.new("RGB", (50, 50), color="red")
    img_path = tmp_path / "red.png"
    img.save(str(img_path))

    vlm = MockVLM(response=SAMPLE_TIKZ)
    agent = TikZExporterAgent(vlm)

    await agent.run(
        image_path=str(img_path),
        source_context="ctx",
        caption="cap",
    )

    assert vlm.last_images is not None
    assert len(vlm.last_images) == 1


@pytest.mark.asyncio
async def test_run_plot_type(tmp_path):
    """run() with STATISTICAL_PLOT loads the plot prompt."""
    from PIL import Image

    img = Image.new("RGB", (50, 50), color="blue")
    img_path = tmp_path / "plot.png"
    img.save(str(img_path))

    vlm = MockVLM(response=f"```pgfplots\n{SAMPLE_PGFPLOTS}\n```")
    agent = TikZExporterAgent(vlm)

    result = await agent.run(
        image_path=str(img_path),
        source_context="data",
        caption="plot caption",
        diagram_type=DiagramType.STATISTICAL_PLOT,
    )

    assert "% Diagram type: statistical_plot" in result
    assert SAMPLE_PGFPLOTS in result


@pytest.mark.asyncio
async def test_run_optional_description(tmp_path):
    """run() works when description is None."""
    from PIL import Image

    img = Image.new("RGB", (50, 50))
    img_path = tmp_path / "img.png"
    img.save(str(img_path))

    vlm = MockVLM(response=SAMPLE_TIKZ)
    agent = TikZExporterAgent(vlm)

    result = await agent.run(
        image_path=str(img_path),
        source_context="ctx",
        caption="cap",
        description=None,
    )

    assert "not available" in vlm.last_prompt
    assert SAMPLE_TIKZ in result
