"""End-to-end test for TikZ export through the full pipeline."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

pytest.importorskip("PIL", reason="PIL/Pillow required for pipeline image mock")
from PIL import Image

from paperbanana.core.config import Settings
from paperbanana.core.pipeline import PaperBananaPipeline
from paperbanana.core.types import (
    DiagramType,
    GenerationInput,
    PipelineProgressEvent,
    PipelineProgressStage,
)

_TIKZ_RESPONSE = """```latex
\\begin{tikzpicture}
  \\node[draw] (a) at (0,0) {Encoder};
  \\node[draw] (b) at (3,0) {Decoder};
  \\draw[->] (a) -- (b);
\\end{tikzpicture}
```"""


class _MockVLM:
    name = "mock-vlm"
    model_name = "mock-model"

    def __init__(self, responses: list[str]):
        self._responses = responses
        self._idx = 0

    async def generate(self, *args, **kwargs):
        idx = min(self._idx, len(self._responses) - 1)
        self._idx += 1
        return self._responses[idx]


class _MockImageGen:
    name = "mock-image-gen"
    model_name = "mock-image-model"

    async def generate(self, *args, **kwargs):
        return Image.new("RGB", (128, 128), color=(255, 255, 255))


@pytest.mark.asyncio
async def test_pipeline_export_tikz_writes_tex_file(tmp_path):
    """With export_tikz=True the pipeline writes a .tex next to the image
    and sets tikz_path on GenerationOutput."""
    settings = Settings(
        output_dir=str(tmp_path / "outputs"),
        reference_set_path=str(tmp_path / "empty_refs"),
        refinement_iterations=1,
        save_iterations=False,
        export_tikz=True,
    )
    vlm = _MockVLM(
        responses=[
            "Initial plan description",
            "Styled final description",
            json.dumps({"critic_suggestions": [], "revised_description": None}),
            _TIKZ_RESPONSE,
        ]
    )
    image_gen = _MockImageGen()
    pipeline = PaperBananaPipeline(settings=settings, vlm_client=vlm, image_gen_fn=image_gen)

    result = await pipeline.generate(
        GenerationInput(
            source_context="Minimal context",
            communicative_intent="Minimal caption",
            diagram_type=DiagramType.METHODOLOGY,
        ),
    )

    assert result.tikz_path is not None
    tex_path = Path(result.tikz_path)
    assert tex_path.exists()
    assert tex_path.suffix == ".tex"
    assert tex_path == Path(result.image_path).with_suffix(".tex")

    content = tex_path.read_text(encoding="utf-8")
    assert content.startswith("% Generated by PaperBanana")
    assert "\\begin{tikzpicture}" in content
    assert "\\end{tikzpicture}" in content

    assert result.metadata.get("tikz_path") == result.tikz_path


@pytest.mark.asyncio
async def test_pipeline_export_tikz_disabled_by_default(tmp_path):
    """Without export_tikz, no .tex file is produced and tikz_path is None."""
    settings = Settings(
        output_dir=str(tmp_path / "outputs"),
        reference_set_path=str(tmp_path / "empty_refs"),
        refinement_iterations=1,
        save_iterations=False,
    )
    vlm = _MockVLM(
        responses=[
            "Initial plan description",
            "Styled final description",
            json.dumps({"critic_suggestions": [], "revised_description": None}),
        ]
    )
    image_gen = _MockImageGen()
    pipeline = PaperBananaPipeline(settings=settings, vlm_client=vlm, image_gen_fn=image_gen)

    result = await pipeline.generate(
        GenerationInput(
            source_context="Minimal context",
            communicative_intent="Minimal caption",
            diagram_type=DiagramType.METHODOLOGY,
        ),
    )

    assert result.tikz_path is None
    assert not Path(result.image_path).with_suffix(".tex").exists()


@pytest.mark.asyncio
async def test_pipeline_export_tikz_failure_is_surfaced(tmp_path, monkeypatch):
    """A TikZ export failure does not break the run and is reported via the
    TIKZ_EXPORTER_END progress event with an error payload."""
    events: list[PipelineProgressEvent] = []

    settings = Settings(
        output_dir=str(tmp_path / "outputs"),
        reference_set_path=str(tmp_path / "empty_refs"),
        refinement_iterations=1,
        save_iterations=False,
        export_tikz=True,
    )
    vlm = _MockVLM(
        responses=[
            "Initial plan description",
            "Styled final description",
            json.dumps({"critic_suggestions": [], "revised_description": None}),
        ]
    )
    image_gen = _MockImageGen()
    pipeline = PaperBananaPipeline(settings=settings, vlm_client=vlm, image_gen_fn=image_gen)

    async def _boom(*args, **kwargs):
        raise RuntimeError("VLM exploded")

    monkeypatch.setattr(pipeline.tikz_exporter, "run", _boom)

    result = await pipeline.generate(
        GenerationInput(
            source_context="Minimal context",
            communicative_intent="Minimal caption",
            diagram_type=DiagramType.METHODOLOGY,
        ),
        progress_callback=events.append,
    )

    # Image generation still succeeds; no .tex is produced.
    assert Path(result.image_path).exists()
    assert result.tikz_path is None

    end_events = [e for e in events if e.stage == PipelineProgressStage.TIKZ_EXPORTER_END]
    assert len(end_events) == 1
    assert end_events[0].extra is not None
    assert "VLM exploded" in (end_events[0].extra.get("error") or "")
