"""TikZ Exporter Agent: Converts generated images to LaTeX/TikZ source code."""

from __future__ import annotations

import re
from typing import Optional

import structlog

from paperbanana.agents.base import BaseAgent
from paperbanana.core.types import DiagramType
from paperbanana.core.utils import load_image
from paperbanana.providers.base import VLMProvider

logger = structlog.get_logger()

# Header comment template embedded in every exported .tex file.
_HEADER_TEMPLATE = """\
% Generated by PaperBanana {version}
% Source: {source_label}
% Model: {model}
% Venue: {venue}
% Diagram type: {diagram_type}
"""


class TikZExporterAgent(BaseAgent):
    """Converts a generated academic illustration to compilable LaTeX/TikZ source.

    For methodology diagrams the agent emits a standalone TikZ picture. For
    statistical plots it emits PGFPlots markup.  The output is a self-contained
    snippet that can be pasted directly into any LaTeX document.

    Note: Generated LaTeX is not compile-validated; test in your LaTeX
    environment.
    """

    def __init__(
        self,
        vlm_provider: VLMProvider,
        prompt_dir: str = "prompts",
        prompt_recorder=None,
    ):
        super().__init__(vlm_provider, prompt_dir, prompt_recorder=prompt_recorder)

    @property
    def agent_name(self) -> str:
        return "tikz_exporter"

    async def run(
        self,
        image_path: str,
        source_context: str,
        caption: str,
        diagram_type: DiagramType = DiagramType.METHODOLOGY,
        description: Optional[str] = None,
        source_label: str = "",
        model_label: str = "",
        venue: str = "neurips",
        version: str = "",
    ) -> str:
        """Convert a generated image to TikZ/PGFPlots source.

        Args:
            image_path: Path to the generated image to convert.
            source_context: Original methodology text (used as context).
            caption: Figure caption / communicative intent.
            diagram_type: METHODOLOGY → TikZ; STATISTICAL_PLOT → PGFPlots.
            description: Optimised description from the planner/stylist (optional).
            source_label: Human-readable label for the header comment.
            model_label: VLM/image-gen model label for the header comment.
            venue: Target venue (neurips, icml, …).
            version: PaperBanana version string for the header comment.

        Returns:
            A string containing the complete LaTeX snippet (with header comment).
        """
        image = load_image(image_path)

        prompt_type = "diagram" if diagram_type == DiagramType.METHODOLOGY else "plot"
        template = self.load_prompt(prompt_type)

        desc_block = description.strip() if description else "(not available)"
        prompt = self.format_prompt(
            template,
            prompt_label="tikz_exporter",
            source_context=source_context,
            caption=caption,
            description=desc_block,
        )

        logger.info(
            "Running TikZ exporter",
            image_path=image_path,
            diagram_type=diagram_type.value,
        )

        response = await self.vlm.generate(
            prompt=prompt,
            images=[image],
            temperature=0.2,
            max_tokens=8192,
        )

        tikz_code = self._extract_code(response)

        header = _HEADER_TEMPLATE.format(
            version=version or "unknown",
            source_label=source_label or image_path,
            model=model_label or getattr(self.vlm, "model_name", "unknown"),
            venue=venue,
            diagram_type=diagram_type.value,
        )

        full_output = header + tikz_code
        logger.info("TikZ export complete", output_length=len(full_output))
        return full_output

    @staticmethod
    def _extract_code(response: str) -> str:
        """Strip markdown code fences and return the raw LaTeX/TikZ snippet."""
        # Try to extract content from a fenced block (```latex, ```tikz, ```)
        fenced = re.search(
            r"```(?:latex|tikz|pgfplots|tex)?\s*\n(.*?)```",
            response,
            re.DOTALL | re.IGNORECASE,
        )
        if fenced:
            return fenced.group(1).strip()

        # If the response already looks like raw LaTeX (starts with % or \begin)
        stripped = response.strip()
        if stripped.startswith(("\\begin", "%", "\\tikz")):
            return stripped

        # Best-effort: return the full response trimmed
        return stripped
